import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer";

export const metadata = {
    title: "bodysoulmind - Tanja Bauer",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="de">
            <head>
                <link rel="stylesheet" href="https://use.typekit.net/fcp8bju.css" />{" "}
            </head>

            <body className={` antialiased`}>
                {" "}
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
